### ISSUE TITLE
Only time and date will load when this module is active.

### ISSUE THREAD

**Issue by advokaten** [ronny3050/internet-monitor#1]
As the title says, only my time and date loads when this module is active. I have no idea what's causing this. Is it possible you'd be able to look over this? Everything is on "loading" or "fetching" except time and date. I love the wi-fi connection button! Thanks.

**Comment by ronny3050** [comment]
Did it get fixed?

**Comment by advokaten** [comment]
Yes. I used @pjkoeleman 's settings and it magically worked. I have no idea how though. Thank you for this module!

**Comment by ronny3050** [comment]
Something must have been wrong with your config earlier. You're most welcome! I'm glad this got resolved :)
