### ISSUE TITLE
Update displayStrength more often.

### ISSUE THREAD

**Issue by dherl0623** [ronny3050/internet-monitor#3]
I wondered how to change how often the display strength checks for WiFi strength. I am building a mirror for my girlfriend whose internet gets shut off at night. I would like the display strength symbol to change to the noneColor when it looses connection. During testing I shut off my own WiFi and the icon does not change. Any help would be greatly appreciated! Awesome module by the way!

**Comment by DrewNaylor** [comment]
I don't know exactly what updateInterval controls, but setting that to something above 20000 (for the maxTime default) in the config/config.js file might help. It might not update as soon as the network connection is lost, though.

**Comment by ronny3050** [comment]
`updateInterval` does exactly what you are looking for. Thanks @DrewNaylor 👍
